class_name Verses
## The fifty extra dimensions between the Candy-Verse and the Glitch-Verse.
## Each entry is a recipe for scripts/dim_world.gd:
##   layout  how the place is shaped: grid (city blocks), islands, pillars
##           (towers in a sea), rings, stacks (floating cubes), canyon,
##           giants (you are tiny), maze, spiral, cake, dominoes
##   kit     buildings: city, tall, old, sub (houses), ind (factories), none
##   sky     [top, middle, horizon], sun / shade colours, fog [low, high]
##   ground, ground2, tex (plain, grid, checker, stripes, dots, bricks)
##   sea     [deep, shallow] or [] for a bottomless void
##   wall    building tint, hue = hue shift for buildings and props
##   props   nature-kit models scattered around ("@kit:name" = other kits)
##   giants  the huge things (giant_size = [min, max] height in metres)
##   weather rain, snow, embers, bubbles, leaves, petals, stars, confetti,
##           pixels, ash, sparks, fireflies
##   extra   moon, planet, earth, sun, rainbow, clouds, volcano, balloons, webs
##   bots    [["normal", 8], ["speedy", 2], ["big", 1]]

const LIST := [
	{
		"name": "LAVA-VERSE", "layout": "pillars", "kit": "ind",
		"sky": ["#1a0306", "#6a0f10", "#ff6a1a"], "sun": "#ffd29a", "shade": "#4a0a24",
		"rim": ["#ffcf33", "#ff3a00"], "fog": ["#b3280f", "#3a0610"],
		"ground": "#4a3438", "ground2": "#2a1c22", "tex": "stripes", "sea": ["#ff3000", "#ffd000"],
		"wall": "#c8a39a", "props": ["log_large", "campfire_logs"], "weather": "embers", "extra": "volcano",
		"music": "boss", "fall": "TOO HOT!", "bots": [["normal", 6], ["speedy", 2]],
		"intro": ["The floor is LAVA! For real this time!", "Swing from tower to tower. Don't touch the orange stuff!"],
	},
	{
		"name": "JUNGLE-VERSE", "layout": "giants", "kit": "none",
		"sky": ["#0b3b2a", "#2f8a4a", "#d8f07a"], "sun": "#fff2c0", "shade": "#1c4a3a",
		"rim": ["#b8ff5a", "#ffcc33"], "fog": ["#5da04a", "#2a6a3a"],
		"ground": "#3f8a3a", "ground2": "#2f6f2f", "tex": "dots",
		"giants": ["tree_palmTall", "tree_fat", "tree_oak", "tree_default"], "giant_size": [30.0, 55.0],
		"props": ["plant_bushLarge", "flower_redA", "flower_yellowA", "grass_large", "mushroom_redTall"],
		"weather": "leaves", "music": "city", "fall": "WHOOPS!", "bots": [["normal", 6], ["speedy", 3]],
		"intro": ["Whoa, these trees are GIANT!", "Swing through the jungle and find the bots!"],
	},
	{
		"name": "ICE-VERSE", "layout": "islands", "kit": "sub",
		"sky": ["#2a5aa8", "#8fc4ff", "#eaf6ff"], "sun": "#ffffff", "shade": "#5a74b8",
		"rim": ["#ffffff", "#7ae0ff"], "fog": ["#cfe6ff", "#9cc6ff"],
		"ground": "#eef6ff", "ground2": "#bfe0ff", "tex": "plain", "sea": ["#1a4a8a", "#9fe8ff"],
		"wall": "#dfeaff", "hue": 0.55, "props": ["tree_pineTallA_detailed", "tree_pineRoundC"],
		"weather": "snow", "music": "title", "fall": "BRRRR!", "bots": [["normal", 7], ["speedy", 2]],
		"intro": ["Brrr! Everything is frozen!", "Hop across the ice islands. Don't fall in the freezing water!"],
	},
	{
		"name": "DESERT-VERSE", "layout": "canyon", "kit": "none",
		"sky": ["#2a7ad8", "#8ac4f0", "#ffe0a0"], "sun": "#fff0c8", "shade": "#a0584a",
		"rim": ["#ffe070", "#ff8a4a"], "fog": ["#f0c080", "#d8a070"],
		"ground": "#e8b86a", "ground2": "#c8904a", "tex": "stripes", "sea": ["#2a7ab8", "#8ae0e8"],
		"props": ["cactus_tall", "cactus_short", "pot_large", "statue_obelisk"],
		"weather": "ash", "extra": "sun", "music": "city", "fall": "SPLASH!", "bots": [["normal", 7], ["speedy", 2], ["big", 1]],
		"intro": ["Hot hot HOT! A giant desert canyon!", "Watch out for cactus. The bots are hiding in the cliffs!"],
	},
	{
		"name": "TOY-VERSE", "layout": "giants", "kit": "none",
		"sky": ["#3a8aff", "#9ad0ff", "#fff0f8"], "sun": "#ffffff", "shade": "#7a5ad8",
		"rim": ["#ffffff", "#ff5ab8"], "fog": ["#c8e0ff", "#9ac0ff"],
		"ground": "#f0e0c0", "ground2": "#e0c898", "tex": "checker",
		"giants": ["@car:sedan", "@car:truck", "@car:police", "@car:taxi", "@car:van", "@car:ambulance"], "giant_size": [12.0, 18.0],
		"props": ["@plat:coin", "@plat:block-coin"],
		"weather": "confetti", "music": "city", "fall": "WHOOPS!", "bots": [["normal", 6], ["speedy", 2], ["big", 2]],
		"intro": ["Wait... I'm TINY! These are TOY CARS!", "Climb the giant toys and smash those bots!"],
	},
	{
		"name": "MOON-VERSE", "layout": "islands", "kit": "none", "gravity": 0.45,
		"sky": ["#000004", "#05051a", "#20204a"], "sun": "#ffffff", "shade": "#2a2a44",
		"rim": ["#aaccff", "#ffffff"], "fog": ["#101024", "#05050f"], "fog_start": 200.0, "fog_end": 800.0,
		"ground": "#b8b8c0", "ground2": "#8a8a96", "tex": "dots", "sea": [],
		"props": ["statue_block", "@plat:flag"], "weather": "stars", "extra": "earth",
		"music": "title", "fall": "FLOAT AWAY!", "bots": [["normal", 7], ["speedy", 3]],
		"intro": ["We're on the MOON! Look, there's Earth!", "Low gravity! Your jumps go SUPER high!"],
	},
	{
		"name": "PIXEL-VERSE", "layout": "stacks", "kit": "none",
		"sky": ["#2020a0", "#4a6aff", "#8ae0ff"], "sun": "#ffffff", "shade": "#302080",
		"rim": ["#ffffff", "#ff4ad8"], "fog": ["#6a9aff", "#3a5ae0"],
		"ground": "#5ad84a", "ground2": "#a0582a", "tex": "checker", "sea": ["#1a1a6a", "#3a8aff"],
		"props": ["@plat:block-coin", "@plat:brick", "tree_blocks"], "weather": "pixels", "extra": "clouds",
		"music": "city", "fall": "GAME OVER... JK!", "bots": [["normal", 7], ["speedy", 3]],
		"intro": ["Everything is made of PIXELS!", "It's like a video game... inside a video game!"],
	},
	{
		"name": "SPOOKY-VERSE", "layout": "grid", "kit": "old",
		"sky": ["#08020f", "#2a0a3a", "#7a3a8a"], "sun": "#c8b0ff", "shade": "#1a0a2a",
		"rim": ["#9aff5a", "#ff8a1a"], "fog": ["#3a1a4a", "#14081f"], "fog_start": 40.0, "fog_end": 260.0,
		"ground": "#3a3040", "wall": "#8a7aa0", "hue": 0.72,
		"props": ["crop_pumpkin", "tree_detailed_dark", "tree_thin"], "prop_hue": 0.0,
		"weather": "fireflies", "extra": "moon", "music": "title", "fall": "BOO!",
		"bots": [["normal", 8], ["speedy", 2], ["big", 1]],
		"intro": ["Spooky scary skyscrapers...", "Pumpkins everywhere! Smash the bots before they spook YOU!"],
	},
	{
		"name": "NEON-VERSE", "layout": "grid", "kit": "tall",
		"sky": ["#02010a", "#1a0640", "#ff2a8a"], "sun": "#8af0ff", "shade": "#200a40",
		"rim": ["#00ffff", "#ff00d0"], "fog": ["#3a0a5a", "#12042a"],
		"ground": "#1a1030", "wall": "#6a5aa0", "hue": 0.62,
		"weather": "rain", "music": "boss", "fall": "SPLASH!", "bots": [["normal", 7], ["speedy", 3], ["big", 1]],
		"intro": ["NEON lights everywhere! So bright!", "This city never sleeps. Let's smash some bots!"],
	},
	{
		"name": "CLOUD-VERSE", "layout": "islands", "kit": "sub",
		"sky": ["#4aa0ff", "#a8d8ff", "#fff8e8"], "sun": "#ffffff", "shade": "#8a8ad8",
		"rim": ["#ffffff", "#ffd0f0"], "fog": ["#ffffff", "#d8ecff"],
		"ground": "#ffffff", "ground2": "#e8f0ff", "tex": "plain", "sea": ["#e8f0ff", "#ffffff"],
		"wall": "#ffffff", "props": ["@plat:cloud", "tree_default"], "extra": "rainbow",
		"music": "title", "fall": "POOF!", "bots": [["speedy", 5], ["normal", 5]],
		"intro": ["We're walking on CLOUDS!", "Soft and fluffy... but the bots are not!"],
	},
	{
		"name": "TEMPLE-VERSE", "layout": "rings", "kit": "none",
		"sky": ["#2a4ab8", "#7ab0e8", "#ffe8b0"], "sun": "#fff0c8", "shade": "#8a6a5a",
		"rim": ["#ffe070", "#ffffff"], "fog": ["#f0d8a8", "#c8b890"],
		"ground": "#e8dcc0", "ground2": "#c8b890", "tex": "bricks",
		"giants": ["statue_column", "statue_obelisk", "statue_head", "statue_ring"],
		"props": ["pot_large", "statue_columnDamaged", "plant_bushDetailed"],
		"weather": "sparks", "extra": "sun", "music": "title", "fall": "WHOOPS!", "bots": [["normal", 8], ["big", 2]],
		"intro": ["An ancient temple in the sky!", "Giant statues everywhere. Swing from the columns!"],
	},
	{
		"name": "MUSHROOM-VERSE", "layout": "giants", "kit": "none",
		"sky": ["#3a1a6a", "#a05ad8", "#ffd0a0"], "sun": "#fff0e0", "shade": "#4a2a6a",
		"rim": ["#ffe05a", "#ff5a8a"], "fog": ["#b88ad8", "#6a3a9a"],
		"ground": "#6ab84a", "ground2": "#4a9a3a", "tex": "dots",
		"giants": ["mushroom_redTall", "mushroom_tanTall", "mushroom_redGroup"], "giant_size": [30.0, 55.0],
		"props": ["flower_purpleA", "flower_redA", "grass_large"],
		"weather": "petals", "music": "city", "fall": "SQUISH!", "bots": [["normal", 7], ["speedy", 3], ["big", 1]],
		"intro": ["Giant mushrooms! Taller than buildings!", "Bounce around the caps and find the bots!"],
	},
	{
		"name": "FACTORY-VERSE", "layout": "grid", "kit": "ind",
		"sky": ["#2a2a30", "#6a5a50", "#e89a4a"], "sun": "#ffd8a0", "shade": "#3a2a2a",
		"rim": ["#ffb03a", "#ff5a2a"], "fog": ["#8a6a50", "#4a3a34"], "fog_start": 50.0, "fog_end": 300.0,
		"ground": "#5a5250", "wall": "#b0a090",
		"weather": "ash", "music": "boss", "fall": "CLANK!", "bots": [["normal", 8], ["big", 3]],
		"intro": ["A robot factory! This is where bots get MADE!", "Shut it down! Smash them all!"],
	},
	{
		"name": "BEACH-VERSE", "layout": "islands", "kit": "sub",
		"sky": ["#1a8ae8", "#6ac8ff", "#fff0c0"], "sun": "#fffae0", "shade": "#4a8ab8",
		"rim": ["#ffffff", "#ffd05a"], "fog": ["#bfe8ff", "#8ad0ff"],
		"ground": "#f8e0a0", "ground2": "#f0d088", "tex": "plain", "sea": ["#0a6ac8", "#5af0e8"],
		"wall": "#fff0e0", "props": ["tree_palmTall", "tree_palmBend", "@city:detail-parasol-a", "@city:detail-parasol-b"],
		"extra": "sun", "music": "city", "fall": "SPLASH!", "bots": [["normal", 8], ["speedy", 3]],
		"intro": ["Surf's up! A tropical beach!", "No time for sandcastles. Bots at twelve o'clock!"],
	},
	{
		"name": "SPACE-VERSE", "layout": "stacks", "kit": "none", "gravity": 0.6,
		"sky": ["#000000", "#0a0420", "#2a0a5a"], "sun": "#e0e8ff", "shade": "#1a1040",
		"rim": ["#5affff", "#ff5aff"], "fog": ["#1a0a3a", "#050210"], "fog_start": 200.0, "fog_end": 800.0,
		"ground": "#8a8aa8", "ground2": "#5a5a7a", "tex": "grid", "sea": [],
		"props": ["@ind:solar-panel-flat", "@ind:detail-tank"], "weather": "stars", "extra": "planet",
		"music": "boss", "fall": "LOST IN SPACE!", "bots": [["normal", 8], ["speedy", 3]],
		"intro": ["OUTER SPACE! Floating platforms everywhere!", "Low gravity. Big jumps. Big smashes!"],
	},
	{
		"name": "AUTUMN-VERSE", "layout": "grid", "kit": "sub",
		"sky": ["#3a6ac8", "#9ac0e8", "#ffc890"], "sun": "#fff0d8", "shade": "#8a4a4a",
		"rim": ["#ffd05a", "#ff7a3a"], "fog": ["#e8b890", "#b88a70"],
		"ground": "#b8703a", "wall": "#f0e0d0",
		"props": ["tree_oak_fall", "tree_default_fall", "crop_pumpkin"],
		"weather": "leaves", "music": "title", "fall": "CRUNCH!", "bots": [["normal", 8], ["speedy", 3], ["big", 1]],
		"intro": ["Crunchy leaves everywhere. It's fall!", "Rake up the bots! Smash smash smash!"],
	},
	{
		"name": "CRYSTAL-VERSE", "layout": "pillars", "kit": "none",
		"sky": ["#1a0a4a", "#6a3ac8", "#ff9ae8"], "sun": "#f0e0ff", "shade": "#3a1a6a",
		"rim": ["#5affff", "#ff5ae0"], "fog": ["#8a5ad8", "#3a1a7a"],
		"ground": "#9a7ae8", "ground2": "#c8a8ff", "tex": "stripes", "sea": ["#2a0a6a", "#c85aff"],
		"giants": ["statue_obelisk"], "props": ["statue_obelisk"], "prop_hue": 0.72,
		"weather": "sparks", "music": "title", "fall": "SPARKLE!", "bots": [["normal", 8], ["speedy", 3], ["big", 1]],
		"intro": ["Shiny purple crystals everywhere!", "So sparkly! Now smash those bots!"],
	},
	{
		"name": "CHEESE-VERSE", "layout": "pillars", "kit": "none",
		"sky": ["#ff9a2a", "#ffd05a", "#fff8c0"], "sun": "#ffffff", "shade": "#c8781a",
		"rim": ["#ffffff", "#ff5a2a"], "fog": ["#ffd878", "#ffb84a"],
		"ground": "#ffd23a", "ground2": "#e8a81a", "tex": "dots", "sea": ["#e8781a", "#ffd878"],
		"props": ["crop_melon"], "music": "city", "fall": "SPLAT!",
		"bots": [["normal", 9], ["speedy", 2], ["big", 1]],
		"intro": ["Is everything made of... CHEESE?!", "This place smells funny. Smash fast!"],
	},
	{
		"name": "WINTER-VERSE", "layout": "grid", "kit": "sub",
		"sky": ["#6a8ab8", "#b8c8e0", "#f0f0ff"], "sun": "#ffffff", "shade": "#6a78a8",
		"rim": ["#ffffff", "#ff5a5a"], "fog": ["#e0e8f8", "#b8c8e0"], "fog_start": 60.0, "fog_end": 320.0,
		"ground": "#f4f8ff", "wall": "#fff0f0",
		"props": ["tree_pineTallA_detailed", "tree_pineRoundC", "tree_cone"],
		"weather": "snow", "music": "title", "fall": "SNOW PLOP!", "bots": [["normal", 9], ["speedy", 2], ["big", 1]],
		"intro": ["A snowy winter town! Let it snow!", "No snowball fights. BOT fights!"],
	},
	{
		"name": "BRICK-VERSE", "layout": "stacks", "kit": "none",
		"sky": ["#3a8aff", "#7ac0ff", "#d8f4ff"], "sun": "#ffffff", "shade": "#5a4ab8",
		"rim": ["#ffffff", "#ffd83a"], "fog": ["#a8d8ff", "#7ab8ff"],
		"ground": "#c85a2a", "ground2": "#e8883a", "tex": "bricks", "sea": ["#1a4ab8", "#3ab8ff"],
		"props": ["@plat:brick", "@plat:block-coin", "@plat:coin", "@plat:flag"], "extra": "clouds",
		"music": "city", "fall": "BONK!", "bots": [["normal", 8], ["speedy", 3], ["big", 1]],
		"intro": ["Bricks and coins everywhere!", "Jump on the blocks. Then smash the bots!"],
	},
	{
		"name": "STORM-VERSE", "layout": "grid", "kit": "city",
		"sky": ["#05080f", "#1a2a3a", "#4a6a7a"], "sun": "#d0e8ff", "shade": "#1a2030",
		"rim": ["#8ad0ff", "#ffffff"], "fog": ["#2a3a48", "#101820"], "fog_start": 40.0, "fog_end": 240.0,
		"ground": "#2a3038", "wall": "#8090a0", "lightning": true,
		"weather": "rain", "music": "boss", "fall": "SPLOOSH!", "bots": [["normal", 9], ["speedy", 3], ["big", 1]],
		"intro": ["A HUGE storm! Thunder and lightning!", "The bots love the rain. Let's rain on THEIR parade!"],
	},
	{
		"name": "SWAMP-VERSE", "layout": "islands", "kit": "none",
		"sky": ["#1a2a1a", "#3a5a3a", "#9ab86a"], "sun": "#e0f0c0", "shade": "#1a3a2a",
		"rim": ["#c8ff5a", "#5aff9a"], "fog": ["#4a6a3a", "#2a3a24"], "fog_start": 30.0, "fog_end": 220.0,
		"ground": "#4a5a2a", "ground2": "#3a4a24", "tex": "dots", "sea": ["#1a2a14", "#5a7a3a"],
		"props": ["log_large", "log_stackLarge", "tree_detailed_dark", "hanging_moss", "mushroom_tanTall", "plant_flatTall"],
		"weather": "fireflies", "music": "title", "fall": "SPLORCH!", "bots": [["normal", 8], ["speedy", 4]],
		"intro": ["Ew, a stinky swamp!", "Stay on the islands. The water is GROSS!"],
	},
	{
		"name": "RETRO-VERSE", "layout": "grid", "kit": "tall",
		"sky": ["#10002a", "#6a0a8a", "#ff8a3a"], "sun": "#ffd0f0", "shade": "#3a0a5a",
		"rim": ["#00f0ff", "#ff3ac8"], "fog": ["#8a1a8a", "#3a0a5a"],
		"ground": "#1a0a3a", "ground2": "#ff3ac8", "tex": "grid", "wall": "#a07ad8", "hue": 0.8,
		"extra": "sun", "music": "city", "fall": "RADICAL!", "bots": [["normal", 9], ["speedy", 4]],
		"intro": ["Totally RADICAL! It's the 1980s!", "Pink sun, purple grid. Time to smash, dude!"],
	},
	{
		"name": "PARTY-VERSE", "layout": "cake", "kit": "none",
		"sky": ["#5a8aff", "#b8a8ff", "#ffd8f0"], "sun": "#ffffff", "shade": "#8a5ac8",
		"rim": ["#ffffff", "#ff5ab8"], "fog": ["#ffd0f0", "#d8c0ff"],
		"ground": "#ffe8f0", "ground2": "#ff8ac8", "tex": "stripes", "sea": ["#ff8ac8", "#ffe0f0"],
		"weather": "confetti", "extra": "balloons", "music": "city", "fall": "FROSTING!",
		"bots": [["normal", 9], ["speedy", 3], ["big", 1]],
		"intro": ["It's a PARTY! Giant birthday cakes!", "The bots crashed the party. Kick them out!"],
	},
	{
		"name": "MAZE-VERSE", "layout": "maze", "kit": "none",
		"sky": ["#2a5a2a", "#7ab87a", "#e8ffc8"], "sun": "#ffffff", "shade": "#2a5a4a",
		"rim": ["#ffffff", "#ffe05a"], "fog": ["#b8e0a0", "#7ab87a"],
		"ground": "#d8c8a0", "ground2": "#3a8a3a", "tex": "plain",
		"props": ["plant_bushLarge", "flower_yellowA"], "music": "title", "fall": "WHOOPS!",
		"bots": [["normal", 9], ["speedy", 4]],
		"intro": ["A giant hedge MAZE!", "Tip: you can climb the walls. Or swing right over them!"],
	},
	{
		"name": "FARM-VERSE", "layout": "giants", "kit": "none",
		"sky": ["#3a8ae8", "#8ac8ff", "#fff0c0"], "sun": "#fff8e0", "shade": "#6a6a3a",
		"rim": ["#ffffff", "#ffd05a"], "fog": ["#d8f0c0", "#a8d0a0"],
		"ground": "#8a5a3a", "ground2": "#6ab84a", "tex": "stripes",
		"giants": ["crop_pumpkin", "crop_carrot", "crop_melon", "crops_cornStageD"], "giant_size": [25.0, 60.0],
		"props": ["crops_cornStageD", "tree_default", "@sub:fence"],
		"extra": "sun", "music": "city", "fall": "MOO!", "bots": [["normal", 9], ["speedy", 3], ["big", 2]],
		"intro": ["Giant veggies! That carrot is a SKYSCRAPER!", "Eat your vegetables... I mean, SMASH the bots!"],
	},
	{
		"name": "SHADOW-VERSE", "layout": "grid", "kit": "city",
		"sky": ["#ff5a1a", "#ffa04a", "#fff0a0"], "sun": "#402030", "shade": "#0a0408",
		"rim": ["#ffd05a", "#ff5a1a"], "fog": ["#ff8a3a", "#ff5a1a"],
		"ground": "#1a0a10", "wall": "#201018",
		"extra": "sun", "music": "title", "fall": "WHOOPS!", "bots": [["normal", 10], ["speedy", 3]],
		"intro": ["Everything is a SHADOW!", "Only the bots glow. Find them!"],
	},
	{
		"name": "RUINS-VERSE", "layout": "rings", "kit": "none",
		"sky": ["#2a5a4a", "#6aa88a", "#f0f0c0"], "sun": "#fff8d0", "shade": "#3a4a3a",
		"rim": ["#e0ff8a", "#ffd05a"], "fog": ["#a8c8a0", "#6a8a6a"],
		"ground": "#a8a890", "ground2": "#7a8a6a", "tex": "bricks",
		"giants": ["statue_columnDamaged", "statue_column", "statue_head"],
		"props": ["tree_fat", "plant_bushLarge", "hanging_moss", "statue_block"],
		"weather": "leaves", "music": "title", "fall": "WHOOPS!", "bots": [["normal", 9], ["speedy", 2], ["big", 2]],
		"intro": ["Old ruins, lost in the jungle!", "Broken columns everywhere. Watch your step!"],
	},
	{
		"name": "UNDERWATER-VERSE", "layout": "islands", "kit": "none",
		"sky": ["#021a3a", "#0a5a8a", "#3ac8d8"], "sun": "#c8ffff", "shade": "#0a3a5a",
		"rim": ["#5affe8", "#ff8ac8"], "fog": ["#0a6a8a", "#0a3a5a"], "fog_start": 30.0, "fog_end": 260.0,
		"ground": "#e8d8a0", "ground2": "#c8b880", "tex": "dots", "sea": ["#021a3a", "#0a4a7a"],
		"props": ["plant_flatTall", "mushroom_redGroup", "mushroom_tanTall", "statue_head"], "prop_hue": 0.0,
		"weather": "bubbles", "music": "title", "fall": "BLUB BLUB!", "bots": [["normal", 9], ["speedy", 4]],
		"intro": ["We're UNDER THE SEA!", "Seaweed, coral and... robot sharks? No, just bots!"],
	},
	{
		"name": "MARS-VERSE", "layout": "canyon", "kit": "none", "gravity": 0.7,
		"sky": ["#3a0a0a", "#a03a1a", "#ffb07a"], "sun": "#ffe0c0", "shade": "#5a1a1a",
		"rim": ["#ffb05a", "#ff5a3a"], "fog": ["#c8603a", "#7a2a1a"],
		"ground": "#b8502a", "ground2": "#8a3a1a", "tex": "dots", "sea": [],
		"props": ["statue_block", "@ind:solar-panel-landscape-group", "@plat:flag"], "weather": "ash", "extra": "earth",
		"music": "boss", "fall": "WHOOPS!", "bots": [["normal", 9], ["speedy", 3], ["big", 2]],
		"intro": ["The red planet: MARS!", "Lighter gravity here. Jump across the canyon!"],
	},
	{
		"name": "JELLY-VERSE", "layout": "stacks", "kit": "none", "gravity": 0.6,
		"sky": ["#3a8a3a", "#8ae08a", "#f0ffd0"], "sun": "#ffffff", "shade": "#2a6a5a",
		"rim": ["#ffffff", "#ff5ac8"], "fog": ["#c0f0b0", "#8ad08a"],
		"ground": "#5ae05a", "ground2": "#ff5aa8", "tex": "checker", "sea": ["#2a8a2a", "#a0ff8a"],
		"weather": "bubbles", "music": "city", "fall": "WOBBLE!", "bots": [["normal", 9], ["speedy", 4]],
		"intro": ["Wobbly jiggly JELLY blocks!", "Everything is bouncy here. Boing boing!"],
	},
	{
		"name": "BLUEPRINT-VERSE", "layout": "grid", "kit": "city",
		"sky": ["#0a2a6a", "#1a4aa0", "#5a8ae0"], "sun": "#ffffff", "shade": "#0a2a6a",
		"rim": ["#ffffff", "#8ad0ff"], "fog": ["#2a5ab8", "#1a3a8a"],
		"ground": "#1a4aa8", "ground2": "#ffffff", "tex": "grid", "wall": "#6a9aff", "hue": 0.58,
		"music": "city", "fall": "ERASED!", "bots": [["normal", 10], ["speedy", 3], ["big", 1]],
		"intro": ["This city is just a DRAWING!", "A blueprint world. The bots are real though!"],
	},
	{
		"name": "PENCIL-VERSE", "layout": "grid", "kit": "old", "noir": 1.0, "noir_keep": 0.0,
		"sky": ["#b0b0b0", "#e0e0e0", "#ffffff"], "sun": "#ffffff", "shade": "#606060",
		"rim": ["#ffffff", "#c0c0c0"], "fog": ["#f0f0f0", "#d8d8d8"],
		"ground": "#e8e8e8", "wall": "#ffffff",
		"music": "title", "fall": "SCRIBBLE!", "bots": [["normal", 10], ["speedy", 3], ["big", 1]],
		"intro": ["Everything is a pencil sketch... even ME!", "Grey bots are harder to spot. Look carefully!"],
	},
	{
		"name": "CHESS-VERSE", "layout": "stacks", "kit": "none",
		"sky": ["#1a1a2a", "#5a5a7a", "#d8d8e8"], "sun": "#ffffff", "shade": "#2a2a3a",
		"rim": ["#ffffff", "#ffd05a"], "fog": ["#9a9ab0", "#5a5a7a"],
		"ground": "#f0f0f0", "ground2": "#202020", "tex": "checker", "sea": [],
		"props": ["statue_block", "statue_column", "statue_head"], "music": "title", "fall": "CHECKMATE!",
		"bots": [["normal", 10], ["speedy", 2], ["big", 2]],
		"intro": ["A giant chess board in the sky!", "Your move, bots. SMASH!"],
	},
	{
		"name": "CAMP-VERSE", "layout": "giants", "kit": "none",
		"sky": ["#02041a", "#0a1a3a", "#2a4a6a"], "sun": "#b0c8ff", "shade": "#0a1a2a",
		"rim": ["#ffb05a", "#8ad0ff"], "fog": ["#1a2a3a", "#0a1020"], "fog_start": 40.0, "fog_end": 280.0,
		"ground": "#2a4a2a", "ground2": "#1a3a1a", "tex": "dots",
		"giants": ["tree_pineTallA_detailed", "tree_pineRoundC", "tree_cone"], "giant_size": [35.0, 60.0],
		"props": ["tent_detailedOpen", "campfire_logs", "log_stackLarge"],
		"weather": "fireflies", "extra": "moon", "music": "title", "fall": "OOF!", "bots": [["normal", 10], ["speedy", 3]],
		"intro": ["A spooky forest at night. Campfires!", "Fireflies... and glowing bots. Get 'em!"],
	},
	{
		"name": "GOLDEN-VERSE", "layout": "rings", "kit": "tall",
		"sky": ["#5a3a0a", "#c8901a", "#fff0a0"], "sun": "#fff8e0", "shade": "#7a4a1a",
		"rim": ["#ffffff", "#ffd83a"], "fog": ["#e8c060", "#b8882a"],
		"ground": "#ffd84a", "ground2": "#e8b02a", "tex": "grid", "wall": "#ffd060", "hue": 0.12,
		"giants": ["@plat:coin"], "centre_size": [40.0, 48.0], "prop_hue": 0.0,
		"weather": "sparks", "extra": "sun", "music": "boss", "fall": "BLING!",
		"bots": [["normal", 10], ["speedy", 2], ["big", 2]],
		"intro": ["Everything is made of GOLD!", "Shiny! But the bots are still bad guys."],
	},
	{
		"name": "SPIRAL-VERSE", "layout": "spiral", "kit": "none",
		"sky": ["#1a3a8a", "#5a8ae8", "#ffd8a0"], "sun": "#ffffff", "shade": "#3a3a8a",
		"rim": ["#ffe05a", "#5affd8"], "fog": ["#a8c0ff", "#6a8ae0"],
		"ground": "#e8e0f0", "ground2": "#8a6ae8", "tex": "stripes", "sea": ["#3a2a8a", "#8a8aff"],
		"music": "city", "fall": "DIZZY!", "bots": [["normal", 10], ["speedy", 3], ["big", 1]],
		"intro": ["A giant spiral tower up to the clouds!", "Climb it, swing it, and smash your way to the top!"],
	},
	{
		"name": "SLIME-VERSE", "layout": "pillars", "kit": "ind",
		"sky": ["#0a1a0a", "#1a5a1a", "#8aff3a"], "sun": "#e0ffc0", "shade": "#1a3a1a",
		"rim": ["#aaff3a", "#3affaa"], "fog": ["#3a8a1a", "#1a3a0a"],
		"ground": "#3a4a3a", "ground2": "#2a3a2a", "tex": "stripes", "sea": ["#2a8a00", "#b8ff3a"],
		"wall": "#a0c090", "weather": "bubbles", "music": "boss", "fall": "SLIMED!",
		"bots": [["normal", 10], ["speedy", 3], ["big", 2]],
		"intro": ["Green goo everywhere! EWWW!", "Don't fall in the slime!"],
	},
	{
		"name": "UPSIDE-DOWN-VERSE", "layout": "grid", "kit": "city", "flip": true,
		"sky": ["#1a0a2a", "#5a2a6a", "#e87a5a"], "sun": "#ffe0d0", "shade": "#3a1a4a",
		"rim": ["#5affff", "#ff8a3a"], "fog": ["#8a4a6a", "#3a1a4a"],
		"ground": "#4a3a5a", "wall": "#c8a0c8", "hue": 0.9,
		"music": "title", "fall": "WHOOPS!", "bots": [["normal", 10], ["speedy", 4], ["big", 1]],
		"intro": ["Look UP! There's a city on the ceiling!", "Two cities for the price of one!"],
	},
	{
		"name": "RAINBOW-VERSE", "layout": "rings", "kit": "tall", "rainbow": true,
		"sky": ["#3a6aff", "#a0c8ff", "#fff0ff"], "sun": "#ffffff", "shade": "#6a5ac8",
		"rim": ["#ffffff", "#ff5ae8"], "fog": ["#e0e8ff", "#b8c8ff"],
		"ground": "#ffffff", "ground2": "#ffd0f0", "tex": "stripes", "wall": "#ffffff",
		"weather": "confetti", "extra": "rainbow", "music": "city", "fall": "WHEEE!",
		"bots": [["normal", 10], ["speedy", 4], ["big", 1]],
		"intro": ["Every colour of the RAINBOW!", "Red, orange, yellow, green... SMASH!"],
	},
	{
		"name": "BLOSSOM-VERSE", "layout": "islands", "kit": "sub",
		"sky": ["#6a8ae8", "#e0b8f0", "#fff0f0"], "sun": "#fffaf0", "shade": "#a06ab8",
		"rim": ["#ffffff", "#ff8ac8"], "fog": ["#ffd8e8", "#e8c0e0"],
		"ground": "#a8e08a", "ground2": "#88c86a", "tex": "plain", "sea": ["#5a8ad8", "#c8e8ff"],
		"wall": "#fff0f4", "props": ["tree_oak_fall", "tree_default_fall", "flower_redA", "flower_purpleA"], "prop_hue": 0.88,
		"weather": "petals", "music": "title", "fall": "SPLASH!", "bots": [["normal", 10], ["speedy", 4], ["big", 1]],
		"intro": ["Pink blossom trees everywhere! So pretty!", "Pretty... until the bots showed up."],
	},
	{
		"name": "ELECTRIC-VERSE", "layout": "pillars", "kit": "none", "lightning": true,
		"sky": ["#02020a", "#0a0a3a", "#3a3aff"], "sun": "#e0f0ff", "shade": "#0a0a2a",
		"rim": ["#ffff3a", "#3affff"], "fog": ["#1a1a6a", "#05051a"],
		"ground": "#2a2a4a", "ground2": "#ffe83a", "tex": "stripes", "sea": ["#0a0a3a", "#5a8aff"],
		"props": ["@ind:chimney-small"], "weather": "sparks", "music": "boss", "fall": "ZZZAP!",
		"bots": [["normal", 10], ["speedy", 5], ["big", 1]],
		"intro": ["ZAP! Electricity everywhere!", "Stay off the water. It's super shocking!"],
	},
	{
		"name": "SUNSET-VERSE", "layout": "grid", "kit": "city",
		"sky": ["#2a1a5a", "#e05a6a", "#ffc85a"], "sun": "#ffd0a0", "shade": "#5a2a5a",
		"rim": ["#ffd05a", "#ff5a8a"], "fog": ["#e8806a", "#8a3a6a"],
		"ground": "#5a3a4a", "wall": "#ffe0d0", "extra": "sun",
		"music": "city", "fall": "SPLASH!", "bots": [["normal", 11], ["speedy", 3], ["big", 1]],
		"intro": ["The most beautiful sunset ever!", "Let's finish before it gets dark!"],
	},
	{
		"name": "MIDNIGHT-VERSE", "layout": "grid", "kit": "tall",
		"sky": ["#000008", "#050a24", "#1a2a5a"], "sun": "#8aa0ff", "shade": "#050a1a",
		"rim": ["#ffe08a", "#5a8aff"], "fog": ["#101a3a", "#05081a"], "fog_start": 50.0, "fog_end": 300.0,
		"ground": "#101828", "wall": "#6070a0",
		"weather": "stars", "extra": "moon", "music": "title", "fall": "SPLASH!", "bots": [["normal", 11], ["speedy", 4]],
		"intro": ["It's midnight. Everyone is sleeping...", "Everyone except the bots. SHHH... then SMASH!"],
	},
	{
		"name": "SATURN-VERSE", "layout": "stacks", "kit": "none", "gravity": 0.7,
		"sky": ["#0a0010", "#2a1030", "#8a4a3a"], "sun": "#fff0e0", "shade": "#2a1a2a",
		"rim": ["#ffd08a", "#8ad0ff"], "fog": ["#4a2a2a", "#1a0a14"], "fog_start": 150.0, "fog_end": 700.0,
		"ground": "#d8b890", "ground2": "#b08a6a", "tex": "stripes", "sea": [],
		"props": ["@ind:detail-tank-large", "@plat:flag"], "weather": "stars", "extra": "planet",
		"music": "boss", "fall": "WHOOSH!", "bots": [["normal", 11], ["speedy", 3], ["big", 1]],
		"intro": ["Look at those RINGS! We're near Saturn!", "Floaty gravity. Jump big!"],
	},
	{
		"name": "MEGA-VERSE", "layout": "giants", "kit": "none",
		"sky": ["#3a4aa8", "#8a9ae0", "#ffe0c8"], "sun": "#ffffff", "shade": "#4a3a8a",
		"rim": ["#ffe05a", "#ff5a5a"], "fog": ["#c0c8f0", "#8a9ae0"],
		"ground": "#7ac85a", "ground2": "#6ab84a", "tex": "plain",
		"giants": ["@sub:building-type-a", "@sub:building-type-c", "@sub:building-type-k", "@sub:tree-large"], "giant_size": [30.0, 45.0],
		"props": ["@sub:fence", "@sub:planter"],
		"music": "boss", "fall": "WHOOPS!", "bots": [["big", 7], ["normal", 4]],
		"intro": ["MEGA houses! MEGA trees! MEGA-BOTS!", "Only MEGA-BOTS here. Hit them lots of times!"],
	},
	{
		"name": "SPEED-VERSE", "layout": "canyon", "kit": "none",
		"sky": ["#1a3aa8", "#5a8aff", "#ffe8a0"], "sun": "#ffffff", "shade": "#3a3a8a",
		"rim": ["#ffff5a", "#ff5a3a"], "fog": ["#b8c8ff", "#7a8ae0"],
		"ground": "#e8e8f0", "ground2": "#ff3a3a", "tex": "stripes", "sea": ["#1a3a8a", "#5ab8ff"],
		"props": ["@roads:construction-cone", "@plat:flag"],
		"music": "city", "fall": "SPLASH!", "bots": [["speedy", 12]],
		"intro": ["The SPEED-VERSE! Everything is FAST!", "Only speedy bots here. Catch them if you can!"],
	},
	{
		"name": "DOMINO-VERSE", "layout": "dominoes", "kit": "none",
		"sky": ["#2a1a4a", "#6a5a9a", "#e0d0ff"], "sun": "#ffffff", "shade": "#2a2a4a",
		"rim": ["#ffffff", "#ffd05a"], "fog": ["#a898d0", "#6a5a9a"],
		"ground": "#2a8a4a", "ground2": "#207a3a", "tex": "plain", "sea": [],
		"music": "city", "fall": "WHOOPS!", "bots": [["normal", 11], ["speedy", 4], ["big", 1]],
		"intro": ["Giant DOMINOES as tall as towers!", "Swing through the domino maze!"],
	},
	{
		"name": "NIGHTMARE-VERSE", "layout": "pillars", "kit": "old", "lightning": true,
		"sky": ["#0a0000", "#3a0000", "#a01a1a"], "sun": "#ffb0a0", "shade": "#1a0005",
		"rim": ["#ff3a3a", "#ffffff"], "fog": ["#4a0a0a", "#1a0003"],
		"ground": "#2a1a1a", "ground2": "#1a0a0a", "tex": "plain", "sea": ["#1a0000", "#8a0a0a"],
		"wall": "#8a6a6a", "props": ["tree_thin", "tree_detailed_dark"], "weather": "ash", "extra": "moon",
		"music": "boss", "fall": "AAAH!", "bots": [["normal", 11], ["speedy", 4], ["big", 2]],
		"intro": ["This is the scariest dimension yet...", "Be brave, spider! You're almost there!"],
	},
	{
		"name": "WEB-VERSE", "layout": "rings", "kit": "tall", "webs": true,
		"sky": ["#0a0a2a", "#3a1a6a", "#ff5a8a"], "sun": "#ffe0f0", "shade": "#2a0a4a",
		"rim": ["#ff3a5a", "#3a8aff"], "fog": ["#5a2a7a", "#1a0a3a"],
		"ground": "#2a1a3a", "ground2": "#ff3a5a", "tex": "grid", "wall": "#c05a7a", "hue": 0.95,
		"weather": "sparks", "extra": "moon", "music": "boss", "fall": "THWIP!",
		"bots": [["normal", 12], ["speedy", 4], ["big", 2]],
		"intro": ["The WEB-VERSE: home of all the spiders!", "The Glitch-Verse is next. Smash these bots and GO!"],
	},
]


static func count() -> int:
	return LIST.size()


static func get_theme(i: int) -> Dictionary:
	return LIST[i]
